### ISSUE TITLE
GPL-3.0 violation notice

### ISSUE THREAD

**Issue by 161chihuahuas** [MicroMinion/mm-services-kademlia#19]
Hi friends,

I'm writing you today to bring an issue to your attention regarding the use of the [kad](https://github.com/kadtools/kad) package in [mm-services-kademlia](https://github.com/MicroMinion/mm-services-kademlia). Since it was first authored, the kad package [has been licensed under GNU General Public License version 3](https://github.com/kadtools/kad/blob/v0.1.0/LICENSE) (until the latest 2.0.0 release changed to the GNU Affero General Public License version 3).

The GPL requires that derivative works also be licensed under the GPL. I understand this is sometimes a contention point in the free software and open source community, but as the author of the kad package, I chose the license to ensure that my work would always respects user's rights. 

I see that much of kad's source code has been embedded in this package, particularly with the LICENSE file and attribution stripped. This package is also licensed under the MIT license which does not satisfy the requirements of the GPL. I am certain this was not done with any ill intent and may likely have happened due to a misunderstanding of the GPL.

The simplest way to fix this would be to resolve the following:

* License and copyright notice
  * [ ] The original README includes this, so just move a copy over
  * [ ] This package as a derivative must be licensed under the GPL 

Thanks for your understanding. If you have any questions, please feel free to ask. Keep up the great work and happy hacking!

**Comment by thomasdelaet** [comment]
Dear Gordon

Apologies. This is sloppiness on my side. Software is not yet used and we did not yet do thorough licensing check. I will fix this.

Again apologies and thanks for making KAD available as open-source!

**Comment by 161chihuahuas** [comment]
:+1: :heart:
